services:
  db:
    build: ./postgres
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: location_app
      TZ: "Asia/Tokyo"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  backend:
    hostname: golang
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    hostname: nginx
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
volumes:
  db_data: